# Generated by Django 4.0 on 2023-05-24 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_created_date_alter_cars_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 21, 0, 3, 465315)),
        ),
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
