# Generated by Django 4.0 on 2023-05-24 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_created_date_alter_cars_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 21, 4, 46, 714810)),
        ),
        migrations.AlterField(
            model_name='cars',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
    ]
